/** Generated by scripts/assets.mjs — do not edit by hand.
 *
 * Every image in Aaina is a crop of a named, CC0-licensed Indian painting, held by a museum that
 * has waived copyright in writing. No stock photography, no generated imagery, no human faces.
 */
export interface Plate {
  slug: string; title: string; date: string; school: string; holder: string; acc: string; page: string
}

export const PLATES: Plate[] = [
  {
    "slug": "parrot",
    "title": "Green Parrot",
    "date": "c. 1820",
    "school": "Company School",
    "holder": "Cleveland Museum of Art",
    "acc": "1972.285",
    "page": "https://clevelandart.org/art/1972.285"
  },
  {
    "slug": "hoopoe",
    "title": "Hoopoe on a Citrus Tree Branch",
    "date": "c. 1800",
    "school": "Company School, Calcutta",
    "holder": "Cleveland Museum of Art",
    "acc": "1990.67",
    "page": "https://clevelandart.org/art/1990.67"
  },
  {
    "slug": "falcon",
    "title": "Falcon on a Perch",
    "date": "c. 1610",
    "school": "Rajput Kingdom of Amber",
    "holder": "Cleveland Museum of Art",
    "acc": "2018.165",
    "page": "https://clevelandart.org/art/2018.165"
  },
  {
    "slug": "horse",
    "title": "A Saddled Horse",
    "date": "c. 1750",
    "school": "Pahari kingdoms",
    "holder": "Cleveland Museum of Art",
    "acc": "1968.106",
    "page": "https://clevelandart.org/art/1968.106"
  },
  {
    "slug": "shri-raga",
    "title": "Shri Raga, from a Ragamala",
    "date": "c. 1695",
    "school": "Mewar",
    "holder": "Cleveland Museum of Art",
    "acc": "1931.451",
    "page": "https://clevelandart.org/art/1931.451"
  },
  {
    "slug": "maru-ragini",
    "title": "Maru Ragini, from a Ragamala",
    "date": "1650–80",
    "school": "Amber / Deccan",
    "holder": "Cleveland Museum of Art",
    "acc": "2018.168",
    "page": "https://clevelandart.org/art/2018.168"
  },
  {
    "slug": "dyer",
    "title": "Man Dyeing Cloth",
    "date": "early 1830s",
    "school": "Company School, Lucknow",
    "holder": "Cleveland Museum of Art",
    "acc": "1992.142",
    "page": "https://clevelandart.org/art/1992.142"
  },
  {
    "slug": "utka",
    "title": "Utka Nayika — the heroine who waits",
    "date": "c. 1800",
    "school": "Pahari",
    "holder": "Cleveland Museum of Art",
    "acc": "1932.118",
    "page": "https://clevelandart.org/art/1932.118"
  },
  {
    "slug": "fruit-bat",
    "title": "Great Indian Fruit Bat",
    "date": "c. 1777–82",
    "school": "Bhawani Das, Company School, Calcutta",
    "holder": "The Metropolitan Museum of Art",
    "acc": "2008.312",
    "page": "https://www.metmuseum.org/art/collection/search/456949"
  },
  {
    "slug": "stork",
    "title": "Black Stork in a Landscape",
    "date": "c. 1780",
    "school": "Company School",
    "holder": "The Metropolitan Museum of Art",
    "acc": "2008.313",
    "page": "https://www.metmuseum.org/art/collection/search/454011"
  }
]

export const PLATE_BY_SLUG: Record<string, Plate> = Object.fromEntries(PLATES.map((p) => [p.slug, p]))

export function plateSrc(slug: string): string {
  return `/plates/${slug}.jpg`
}

export function attribution(p: Plate): string {
  return `${p.title}, ${p.date}. ${p.school}. ${p.holder} (${p.acc}). CC0.`
}
