import type { Item } from "../types";
import {
  agree9,
  agree7,
  bipolar7,
  csiExtent,
  csiFrequency,
  csiHappiness,
  csiTruth,
  likely9,
  true7,
  trust7,
} from "./scales";

/** CORE DIMENSIONS — the validated mainstream of relationship science.
 *  Item text is verbatim from the published instruments except where a note
 *  says otherwise; every adaptation is disclosed in SCIENCE-v2.md §Adaptations. */

/* ---------------------------- Satisfaction (CSI) --------------------------- */

export const SATISFACTION_ITEMS: Item[] = [
  {
    id: "sat-1",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "All things considered, how happy are you in your relationship?",
    scale: csiHappiness,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-2",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "In general, how often do you think that things between you and your partner are going well?",
    scale: csiFrequency,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-3",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "Our relationship is strong.",
    scale: csiTruth,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-4",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "My relationship with my partner makes me happy.",
    scale: csiTruth,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-5",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "I have a warm and comfortable relationship with my partner.",
    scale: csiTruth,
    citation: "funk-rogge-2007",
  },
  {
    id: "sat-6",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "I really feel like part of a team with my partner.",
    scale: csiTruth,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-7",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "How rewarding is your relationship with your partner?",
    scale: csiExtent,
    citation: "funk-rogge-2007",
  },
  {
    id: "sat-8",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "How well does your partner meet your needs?",
    scale: csiExtent,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-9",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "In general, how satisfied are you with your relationship?",
    scale: csiExtent,
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-10",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "My relationship, most days, feels…",
    scale: bipolar7("empty", "full"),
    citation: "funk-rogge-2007",
    echoable: true,
  },
  {
    id: "sat-11",
    dimension: "satisfaction",
    section: "the-feeling",
    text: "When you think about the relationship as a whole, it feels…",
    scale: bipolar7("discouraging", "hopeful"),
    citation: "funk-rogge-2007",
    echoable: true,
  },
];

/* ------------------------- Commitment (Investment Model) ------------------- */

export const COMMITMENT_ITEMS: Item[] = [
  {
    id: "com-1",
    dimension: "commitment",
    section: "the-future",
    text: "I am committed to maintaining my relationship with my partner.",
    scale: agree9,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-2",
    dimension: "commitment",
    section: "the-future",
    text: "I want our relationship to last for a very long time.",
    scale: agree9,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-3",
    dimension: "commitment",
    section: "the-future",
    text: "I feel very attached to our relationship — very strongly linked to my partner.",
    scale: agree9,
    citation: "rusbult-1998",
  },
  {
    id: "com-4",
    dimension: "commitment",
    section: "the-future",
    text: "It is likely that I will be with someone other than my partner within the next year.",
    scale: agree9,
    reverse: true,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-5",
    dimension: "commitment",
    section: "the-future",
    text: "I would not feel very upset if our relationship were to end in the near future.",
    scale: agree9,
    reverse: true,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-6",
    dimension: "commitment",
    section: "the-future",
    text: "I want our relationship to last forever.",
    scale: agree9,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-7",
    dimension: "commitment",
    section: "the-future",
    text: "I imagine being with my partner several years from now.",
    scale: agree9,
    citation: "rusbult-1998",
    echoable: true,
  },
  {
    id: "com-8",
    dimension: "commitment",
    section: "the-future",
    text: "I have put a great deal into our relationship that I would lose if it ended.",
    scale: agree9,
    citation: "rusbult-1998",
  },
  {
    id: "com-9",
    dimension: "commitment",
    section: "the-future",
    text: "If I weren't with my partner, I would do fine — I would find another appealing person to be with.",
    scale: agree9,
    reverse: true,
    citation: "rusbult-1998",
    echoable: true,
  },
];

/* ------------------------------ Attachment (ECR-S) ------------------------- */

export const ATTACHMENT_ITEMS: Item[] = [
  // Anxiety
  {
    id: "anx-1",
    dimension: "attachment-anxiety",
    section: "you",
    text: "I need a lot of reassurance that I am loved by my partner.",
    scale: agree7,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "anx-2",
    dimension: "attachment-anxiety",
    section: "you",
    text: "I find that my partner doesn't want to get as close as I would like.",
    scale: agree7,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "anx-3",
    dimension: "attachment-anxiety",
    section: "you",
    text: "My desire to be very close sometimes scares people away.",
    scale: agree7,
    citation: "wei-2007",
  },
  {
    id: "anx-4",
    dimension: "attachment-anxiety",
    section: "you",
    text: "I do not often worry about being abandoned.",
    scale: agree7,
    reverse: true,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "anx-5",
    dimension: "attachment-anxiety",
    section: "you",
    text: "I get frustrated if my partner is not available when I need them.",
    scale: agree7,
    citation: "wei-2007",
  },
  {
    id: "anx-6",
    dimension: "attachment-anxiety",
    section: "you",
    text: "I worry that my partner won't care about me as much as I care about them.",
    scale: agree7,
    citation: "wei-2007",
    echoable: true,
  },
  // Avoidance (item text is in the avoidance direction; dimension is inverted in scoring)
  {
    id: "avo-1",
    dimension: "attachment-avoidance",
    section: "you",
    text: "It helps to turn to my romantic partner in times of need.",
    scale: agree7,
    reverse: true,
    citation: "wei-2007",
  },
  {
    id: "avo-2",
    dimension: "attachment-avoidance",
    section: "you",
    text: "I want to get close to my partner, but I keep pulling back.",
    scale: agree7,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "avo-3",
    dimension: "attachment-avoidance",
    section: "you",
    text: "I turn to my partner for many things, including comfort and reassurance.",
    scale: agree7,
    reverse: true,
    citation: "wei-2007",
  },
  {
    id: "avo-4",
    dimension: "attachment-avoidance",
    section: "you",
    text: "I try to avoid getting too close to my partner.",
    scale: agree7,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "avo-5",
    dimension: "attachment-avoidance",
    section: "you",
    text: "I usually discuss my problems and concerns with my partner.",
    scale: agree7,
    reverse: true,
    citation: "wei-2007",
    echoable: true,
  },
  {
    id: "avo-6",
    dimension: "attachment-avoidance",
    section: "you",
    text: "I am nervous when my partner gets too close to me.",
    scale: agree7,
    citation: "wei-2007",
  },
];

/* ------------------------------ Conflict (CPQ) ----------------------------- */

export const CONFLICT_ITEMS: Item[] = [
  {
    id: "cfl-1",
    dimension: "conflict-pattern",
    section: "friction",
    text: "When an issue arises, both of us try to discuss it.",
    scale: likely9,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-2",
    dimension: "conflict-pattern",
    section: "friction",
    text: "When an issue arises, both of us avoid discussing the problem.",
    scale: likely9,
    reverse: true,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-3",
    dimension: "conflict-pattern",
    section: "friction",
    text: "During a discussion, both of us express our feelings to each other.",
    scale: likely9,
    citation: "christensen-1990",
  },
  {
    id: "cfl-4",
    dimension: "conflict-pattern",
    section: "friction",
    text: "During a discussion, both of us suggest possible solutions and compromises.",
    scale: likely9,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-5",
    dimension: "conflict-pattern",
    section: "friction",
    text: "I pressure, nag, or demand while my partner goes silent or refuses to discuss it further.",
    scale: likely9,
    reverse: true,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-6",
    dimension: "conflict-pattern",
    section: "friction",
    text: "My partner pressures, nags, or demands while I go silent or refuse to discuss it further.",
    scale: likely9,
    reverse: true,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-7",
    dimension: "conflict-pattern",
    section: "friction",
    text: "I criticise while my partner defends themselves.",
    scale: likely9,
    reverse: true,
    citation: "christensen-1990",
  },
  {
    id: "cfl-8",
    dimension: "conflict-pattern",
    section: "friction",
    text: "My partner criticises while I defend myself.",
    scale: likely9,
    reverse: true,
    citation: "christensen-1990",
    echoable: true,
  },
  {
    id: "cfl-9",
    dimension: "conflict-pattern",
    section: "friction",
    text: "After a disagreement, we both end up feeling understood.",
    scale: likely9,
    citation: "christensen-1990",
    echoable: true,
  },
];

/* --------------------------- Responsiveness (PPRS) ------------------------- */

const ppr = (n: number, text: string, echoable = false): Item => ({
  id: `ppr-${n}`,
  dimension: "responsiveness",
  section: "closeness",
  text: `My partner usually ${text}`,
  scale: true7,
  citation: "reis-2004",
  requiresPartner: true,
  echoable,
});

export const RESPONSIVENESS_ITEMS: Item[] = [
  ppr(1, "really listens to me.", true),
  ppr(2, "is responsive to my needs.", true),
  ppr(3, "sees the “real” me.", true),
  ppr(4, "understands me.", true),
  ppr(5, "is on “the same wavelength” with me."),
  ppr(6, "knows me well."),
  ppr(7, "esteems me, shortcomings and all.", true),
  ppr(8, "expresses liking and encouragement for me."),
  ppr(9, "seems interested in what I am thinking and feeling.", true),
  ppr(10, "values my abilities and opinions.", true),
];

/* ------------------------------ Sexual (GMSEX) ----------------------------- */

const gm = (n: number, neg: string, pos: string): Item => ({
  id: `sex-${n}`,
  dimension: "intimacy-sexual",
  section: "closeness",
  text: "In general, how would you describe the physical side of your relationship?",
  scale: bipolar7(neg, pos),
  citation: "lawrance-byers-1995",
  requiresPartner: true,
  echoable: true,
});

export const SEXUAL_ITEMS: Item[] = [
  gm(1, "bad", "good"),
  gm(2, "unpleasant", "pleasant"),
  gm(3, "negative", "positive"),
  gm(4, "unsatisfying", "satisfying"),
  gm(5, "worthless", "valuable"),
];

/* -------------------------------- Trust ----------------------------------- */

export const TRUST_ITEMS: Item[] = [
  {
    id: "trs-1",
    dimension: "trust-security",
    section: "closeness",
    text: "I have found that my partner is unusually dependable, especially when it comes to things which are important to me.",
    scale: trust7,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-2",
    dimension: "trust-security",
    section: "closeness",
    text: "I can rely on my partner to keep the promises they make to me.",
    scale: trust7,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-3",
    dimension: "trust-security",
    section: "closeness",
    text: "I am certain that my partner would not cheat on me, even if the opportunity arose and there was no chance they would get caught.",
    scale: trust7,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-4",
    dimension: "trust-security",
    section: "closeness",
    text: "Though times may change and the future is uncertain, I know my partner will always be ready and willing to offer me strength and support.",
    scale: trust7,
    citation: "rempel-1985",
  },
  {
    id: "trs-5",
    dimension: "trust-security",
    section: "closeness",
    text: "I can rely on my partner to react in a positive way when I expose my weaknesses to them.",
    scale: trust7,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-6",
    dimension: "trust-security",
    section: "closeness",
    text: "My partner is very unpredictable. I never know how they are going to act from one day to the next.",
    scale: trust7,
    reverse: true,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-7",
    dimension: "trust-security",
    section: "closeness",
    text: "I sometimes avoid my partner because they are unpredictable and I fear saying or doing something which might create conflict.",
    scale: trust7,
    reverse: true,
    citation: "rempel-1985",
    echoable: true,
  },
  {
    id: "trs-8",
    dimension: "trust-security",
    section: "closeness",
    text: "My partner behaves in a very consistent manner.",
    scale: trust7,
    citation: "rempel-1985",
  },
];
